### ISSUE TITLE
The readImg function doesn't work on Windows

### ISSUE THREAD

**Issue by mwu-tow** [luna/OpenCV#2]
I have Luna Studio 1.3.0.14 and use this repo at e98e8399238fff4f06ff07e975cebb2627ed07da

When opened the project in Luna Studio, an error appeared on one node:
![image](https://user-images.githubusercontent.com/1548407/43201203-16ebe0a8-9018-11e8-9208-e90680e81310.png)

All other nodes seem to remain in endless "processing" stage.

**Comment by mikusp** [comment]
This is because we try to persuade ImageMagick to operate in a somewhat portable fashion. To make it work, environmental variable MAGICK_CODER_MODULE_PATH must be equal to a path where ImageMagick coder files are located. In OpenCV example, I worked around that by setting the variable at the beginning of main function, like so:
```
import Std.System

def main:
    case System.currentPlatform of
        Windows: System.setEnv "MAGICK_CODER_MODULE_PATH" (Directory.current + "\native_libs\windows")
         _: None
    ...
```
This allow the program to continue, but is not really elegant or sustainable. It's a detail of ImageMagick library, not OpenCV so it should be set in ImageMagick. Furthermore, if ImageMagick was to be used as a dependency, our hack won't work because Directory.current would return the outermost project path, not ImageMagick project path. This could be solved by providing some intrinsic function that would always return path to where the project is located on disk.

**Comment by mikusp** [comment]
@mwu-tow I see that loading coders was corrected on master, so now I merged master into newcore. You can try this now, although if visualizations still don't work, I'll fix them tomorrow in a package. Alternatively, if you want to build Luna Studio, you can use this commit of luna-core while building https://github.com/luna/luna-core/pull/126/commits/19fefcaa80cb445e8639ef409bce93530e50fd56

**Comment by mikusp** [comment]
Should be working on branch newcore

**Comment by sylwiabr** [comment]
should work in Luna Studio 1.4
